(() => {
'use strict';
const E=window.WordPlayEngine,C=E.C,$=id=>document.getElementById(id);
const ui={menu:$('menuScreen'),game:$('gameScreen'),dict:$('dictionaryStatus'),level:$('profileLevel'),best:$('bestScore'),bestWord:$('bestWord'),games:$('gamesPlayed'),unique:$('uniqueWords'),xp:$('careerXpLabel'),xpBar:$('careerXpBar'),cont:$('continueBtn'),contSummary:$('continueSummary'),round:$('roundLabel'),challenge:$('challengeLabel'),mode:$('modeLabel'),roundScore:$('roundScore'),target:$('targetScore'),progress:$('roundProgress'),boss:$('bossBadge'),plays:$('playsLeft'),shuffles:$('shufflesLeft'),rerolls:$('rerollsLeft'),mods:$('modifierList'),modCount:$('modifierCount'),chTitle:$('challengeTitle'),chDesc:$('challengeDescription'),hint:$('wordHint'),preview:$('previewScore'),builder:$('wordBuilder'),combo:$('comboPreview'),board:$('board'),feedback:$('feedback'),total:$('totalScore'),words:$('wordsPlayed'),streak:$('streakValue'),runBest:$('runBestWord'),bestCombo:$('bestCombo'),last:$('lastPlayCard'),goals:$('runGoalList'),backdrop:$('modalBackdrop'),reward:$('rewardModal'),rewardChoices:$('rewardChoices'),rewardRound:$('rewardRoundLabel'),rerollBtn:$('rerollRewardBtn'),info:$('infoModal'),infoTitle:$('infoTitle'),infoBody:$('infoBody'),pause:$('pauseModal'),collection:$('collectionModal'),collectionBody:$('collectionBody'),wordlog:$('wordLogModal'),wordlogList:$('wordLogList'),end:$('endModal'),endEye:$('endEyebrow'),endTitle:$('endTitle'),endStats:$('endStats'),newAchievements:$('newAchievements'),motion:$('reduceMotionToggle'),sound:$('soundToggle')};
let rewardOptions=[];
const fmt=n=>new Intl.NumberFormat('es-ES').format(Math.round(Number(n)||0));
function state(){return E.state}
function showFeedback(t,type=''){ui.feedback.textContent=t;ui.feedback.className=`feedback ${type}`;}
function currentWord(){return state().selected.map(x=>x.char).join('').toLowerCase();}
function showModal(m){ui.backdrop.classList.remove('hidden');[ui.reward,ui.info,ui.pause,ui.collection,ui.wordlog,ui.end].forEach(x=>x.classList.add('hidden'));m.classList.remove('hidden');}
function hideModal(){ui.backdrop.classList.add('hidden');[ui.reward,ui.info,ui.pause,ui.collection,ui.wordlog,ui.end].forEach(x=>x.classList.add('hidden'));}
function renderCareer(){const c=E.career,u=Object.keys(c.words).length,lvl=Math.floor(c.xp/250)+1,within=c.xp%250;ui.best.textContent=fmt(c.bestScore);ui.bestWord.textContent=c.bestWord?c.bestWord.toUpperCase():'—';ui.games.textContent=c.games;ui.unique.textContent=u;ui.level.textContent=`Nivel léxico ${lvl}`;ui.xp.textContent=`${within} / 250 XP`;ui.xpBar.style.width=`${within/250*100}%`;const r=E.loadRun();ui.cont.classList.toggle('hidden',!r);if(r)ui.contSummary.textContent=`Ronda ${r.round} · ${fmt(r.totalScore)} pts`;}
function render(){const s=state();if(!s)return;const ch=E.challenge(s.challenge);ui.mode.textContent=s.mode==='quick'?'PARTIDA RÁPIDA':s.mode==='daily'?'RETO DEL DÍA':'MODO ROGUELIKE';ui.round.textContent=s.mode==='quick'?'10 PALABRAS':`RONDA ${s.round}`;ui.challenge.textContent=ch.title;ui.chTitle.textContent=ch.title;ui.chDesc.textContent=ch.desc;ui.boss.classList.toggle('hidden',ch.kind!=='boss');ui.roundScore.textContent=fmt(s.roundScore);ui.target.textContent=s.mode==='quick'?'∞':fmt(s.target);ui.progress.style.width=s.mode==='quick'?`${Math.min(100,(10-s.playsLeft)*10)}%`:`${Math.min(100,s.roundScore/s.target*100)}%`;ui.plays.textContent=s.playsLeft;ui.shuffles.textContent=s.shufflesLeft;ui.rerolls.textContent=s.rerollsLeft;ui.total.textContent=fmt(s.totalScore);ui.words.textContent=s.words.length;ui.streak.textContent=s.validStreak;ui.runBest.textContent=s.bestPlay?s.bestPlay.word.toUpperCase():'—';ui.bestCombo.textContent=`×${Number(s.bestCombo||1).toFixed(s.bestCombo%1?2:0)}`;renderMods();renderBoard();renderWord();ui.goals.innerHTML=s.goals.map(g=>`<div class="goal-item ${g.done?'done':''}"><span>${g.done?'✓':'○'}</span><span>${g.label}</span></div>`).join('');$('shuffleBtn').disabled=s.shufflesLeft<=0;}
function renderMods(){const s=state();ui.modCount.textContent=s.modifiers.length;if(!s.modifiers.length){ui.mods.className='modifier-list empty-list';ui.mods.innerHTML='<p>Aún no tienes mejoras.</p>';return;}ui.mods.className='modifier-list';ui.mods.innerHTML=s.modifiers.map(id=>C.modifiers.find(x=>x.id===id)).filter(Boolean).map(m=>`<article class="modifier-card rarity-${m.rarity}"><strong>${m.name}<em class="rarity-tag">${m.rarity}</em></strong><span>${m.desc}</span></article>`).join('');}
function renderBoard(){const s=state();ui.board.innerHTML='';for(const t of s.board){const b=document.createElement('button');b.type='button';b.className=`tile ${t.kind} ${s.selected.some(x=>x.id===t.id)?'selected':''}`;b.dataset.value=E.tileScore(t);b.dataset.bonus=t.bonus||0;b.textContent=t.letter;b.addEventListener('click',()=>selectTile(t.id));ui.board.appendChild(b);}}
function selectTile(id){const s=state(),t=s.board.find(x=>x.id===id);if(!t||s.selected.some(x=>x.id===id))return;s.selected.push({id:t.id,char:t.letter});renderBoard();renderWord();}
function renderWord(){const s=state(),w=currentWord();ui.builder.innerHTML='';s.selected.forEach((x,i)=>{const t=s.board.find(q=>q.id===x.id),b=document.createElement('button');b.type='button';b.className=`word-chip ${E.VOWELS.has(E.strip(x.char).toUpperCase())?'vowel':''}`;b.innerHTML=`${x.char}<small>${E.tileScore(t)}</small>`;b.addEventListener('click',()=>{const base=E.strip(x.char).toUpperCase(),cycle=E.ACCENTABLE[base];if(cycle){const j=cycle.indexOf(x.char.toUpperCase());x.char=cycle[(j+1)%cycle.length];renderWord();}else{s.selected.splice(i,1);renderBoard();renderWord();}});ui.builder.appendChild(b);});if(!w){ui.hint.textContent='Selecciona fichas para formar una palabra';ui.preview.textContent='0 pts';ui.combo.innerHTML='';return;}ui.hint.textContent='Pulsa una vocal seleccionada para cambiar su tilde';const tiles=s.selected.map(x=>s.board.find(t=>t.id===x.id)).filter(Boolean),sc=E.score(w,tiles,true);ui.preview.textContent=`${fmt(sc.total)} pts`;ui.combo.innerHTML=sc.effects.slice(0,5).map(e=>`<span class="combo-chip">${e}</span>`).join('');}
function play(){const s=state(),tiles=s.selected.map(x=>s.board.find(t=>t.id===x.id)).filter(Boolean),result=E.play(currentWord(),tiles);if(!result.ok){showFeedback(result.message,result.accent?'warn':'bad');render();return;}s.selected=[];showFeedback(`${result.word.toUpperCase()} · +${fmt(result.score.total)} puntos`,'good');ui.last.className='last-play-card';ui.last.innerHTML=`<div class="played-word">${result.word.toUpperCase()}</div><div class="played-score">+${fmt(result.score.total)} pts</div><div class="effect-list">${result.score.effects.length?result.score.effects.map(e=>`<span>• ${e}</span>`).join(''):'<span>Sin modificadores activos</span>'}</div>`;E.achievements();render();if(s.mode==='quick'&&s.playsLeft<=0)return setTimeout(()=>finish(true),220);if(s.mode!=='quick'&&s.roundScore>=s.target)return setTimeout(openReward,220);if(s.mode!=='quick'&&s.playsLeft<=0)setTimeout(()=>finish(false),220);}
function openReward(){rewardOptions=E.rewards();renderRewards();ui.rewardRound.textContent=`Ronda ${state().round} · ${fmt(state().roundScore)} pts`;ui.rerollBtn.disabled=state().rerollsLeft<=0;showModal(ui.reward);}
function renderRewards(){ui.rewardChoices.innerHTML=rewardOptions.map(r=>`<button class="reward-card rarity-${r.rarity}" data-id="${r.id}" type="button"><span class="reward-type">${r.type==='modifier'?'MODIFICADOR':r.type==='tile'?'FICHA':'RECURSO'} · ${r.rarity}</span><h3>${r.name}</h3><p>${r.desc}</p><div class="reward-footer"><span>${r.type==='modifier'?'Efecto permanente':'Mejora de partida'}</span><strong>Elegir →</strong></div></button>`).join('');ui.rewardChoices.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>choose(rewardOptions.find(r=>r.id===b.dataset.id))));}
function choose(r){E.chooseReward(r);hideModal();if(!E.nextRound())return finish(true);render();showFeedback('Nueva ronda. Busca una combinación potente.','good');}
function reroll(){if(state().rerollsLeft<=0)return;state().rerollsLeft--;rewardOptions=E.rewards();renderRewards();ui.rerollBtn.disabled=state().rerollsLeft<=0;E.saveRun();render();}
function start(mode){E.state=E.newState(mode);E.state.challenge=E.chooseChallenge(1,mode);ui.menu.classList.add('hidden');ui.game.classList.remove('hidden');render();E.saveRun();if(E.career.games===0)howTo(true);}
function resumeRun(){const r=E.loadRun();if(!r)return;E.state=r;ui.menu.classList.add('hidden');ui.game.classList.remove('hidden');render();}
function finish(won){const out=E.finish(won),s=state();ui.endEye.textContent=won?'PARTIDA COMPLETADA':'FIN DE PARTIDA';ui.endTitle.textContent=won?'¡Estrategia completada!':'Tu partida';const stats=[['Puntuación',fmt(s.totalScore)],['Ronda',s.mode==='quick'?'Rápida':`${s.round}/12`],['Palabras',s.words.length],['Más larga',s.longestWord||'—'],['Mejor jugada',s.bestPlay?`${s.bestPlay.word} · ${fmt(s.bestPlay.score)}`:'—'],['XP léxico',`+${out.xp}`]];ui.endStats.innerHTML=stats.map(([a,b])=>`<article><span>${a}</span><strong>${b}</strong></article>`).join('');ui.newAchievements.classList.toggle('hidden',!out.got.length);if(out.got.length)ui.newAchievements.innerHTML=`<strong>🏆 Nuevos logros</strong><div>${out.got.map(a=>a.name).join(' · ')}</div>`;showModal(ui.end);renderCareer();}
function collection(tab='cards'){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const c=E.career;if(tab==='cards')ui.collectionBody.innerHTML=[...C.modifiers,...C.gifts].map(x=>`<article class="collection-card rarity-${x.rarity} ${c.cards[x.id]?'':'locked'}"><strong>${c.cards[x.id]?x.name:'???'}</strong><span>${c.cards[x.id]?x.desc:`${x.rarity} · aún no descubierta`}</span></article>`).join('');else if(tab==='achievements')ui.collectionBody.innerHTML=C.achievements.map(a=>`<article class="collection-card ${c.achievements[a.id]?'':'locked'}"><strong>${c.achievements[a.id]?'🏆':'○'} ${a.name}</strong><span>${a.desc}</span></article>`).join('');else{const words=Object.entries(c.words).sort((a,b)=>b[1]-a[1]);ui.collectionBody.innerHTML=words.map(([w,n])=>`<article class="collection-card"><strong>${w.toUpperCase()}</strong><span>Usada ${n} ${n===1?'vez':'veces'}</span></article>`).join('')||'<article class="collection-card"><strong>Aún vacío</strong><span>Juega palabras para llenar tu archivo.</span></article>';}}
function showCollection(tab){collection(tab);showModal(ui.collection);}
function howTo(first=false){ui.infoTitle.textContent=first?'Primera partida':'Cómo se juega';ui.infoBody.innerHTML='<div class="info-step"><strong>1 · Forma una palabra</strong><br>Selecciona al menos tres fichas.</div><div class="info-step"><strong>2 · Cuida la ortografía</strong><br>Pulsa una vocal seleccionada para A/Á o U/Ú/Ü.</div><div class="info-step"><strong>3 · Supera el objetivo</strong><br>Las palabras largas y letras raras suelen valer más.</div><div class="info-step"><strong>4 · Construye combos</strong><br>Elige una carta tras cada ronda y busca sinergias.</div><div class="info-step"><strong>5 · Rondas jefe</strong><br>Cada tres rondas aparece una regla lingüística especial.</div>';showModal(ui.info);}
function wordLog(){ui.wordlogList.innerHTML=state().wordLog.slice().reverse().map(x=>`<div class="word-log-entry"><strong>${x.word.toUpperCase()}</strong><span>+${fmt(x.score)} pts</span></div>`).join('')||'<p class="empty-list">Aún no has jugado ninguna palabra.</p>';showModal(ui.wordlog);}
function menu(){hideModal();ui.game.classList.add('hidden');ui.menu.classList.remove('hidden');E.state=null;renderCareer();}
function wire(){$('newGameBtn').onclick=()=>start('normal');$('quickGameBtn').onclick=()=>start('quick');$('dailyGameBtn').onclick=()=>start('daily');ui.cont.onclick=resumeRun;$('howToBtn').onclick=()=>howTo(false);$('helpBtn').onclick=()=>howTo(false);$('pauseBtn').onclick=()=>showModal(ui.pause);$('collectionBtn').onclick=()=>showCollection('cards');$('achievementsBtn').onclick=()=>showCollection('achievements');$('closeCollectionBtn').onclick=hideModal;$('closeWordLogBtn').onclick=hideModal;$('wordLogBtn').onclick=wordLog;$('closeInfoBtn').onclick=hideModal;$('resumeBtn').onclick=hideModal;$('saveExitBtn').onclick=()=>{E.saveRun();menu();};$('abandonBtn').onclick=()=>{E.clearRun();menu();};$('undoBtn').onclick=()=>{state().selected.pop();renderBoard();renderWord();};$('clearBtn').onclick=()=>{state().selected=[];renderBoard();renderWord();};$('submitBtn').onclick=play;$('shuffleBtn').onclick=()=>{if(E.shuffle()){showFeedback('Fichas renovadas.','good');render();}};ui.rerollBtn.onclick=reroll;$('playAgainBtn').onclick=()=>{hideModal();start(state()?.mode||'normal');};$('endMenuBtn').onclick=menu;document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>collection(b.dataset.tab));ui.motion.checked=E.settings.reduceMotion;ui.sound.checked=E.settings.sound;ui.motion.onchange=()=>{E.settings.reduceMotion=ui.motion.checked;E.saveSettings();};ui.sound.onchange=()=>{E.settings.sound=ui.sound.checked;E.saveSettings();};document.addEventListener('keydown',e=>{if(ui.game.classList.contains('hidden')||!state()||!ui.backdrop.classList.contains('hidden'))return;if(e.key==='Enter'){e.preventDefault();play();}else if(e.key==='Backspace'){e.preventDefault();state().selected.pop();renderBoard();renderWord();}else if(e.key==='Escape')showModal(ui.pause);else if(/^[a-zñ]$/i.test(e.key)){const t=state().board.find(t=>!state().selected.some(s=>s.id===t.id)&&t.letter===e.key.toUpperCase());if(t)selectTile(t.id);}});}
wire();renderCareer();E.loadDictionary(t=>ui.dict.textContent=t);
})();
