window.WordPlayContent = (() => {
  const modifiers = [
    ['vocalista','Vocalista','common','Empieza por vocal','startsVowel','mult',1.5],
    ['consonante','Entrada fuerte','common','Empieza por consonante','startsConsonant','flat',12],
    ['punto_final','Punto final','common','La última letra es vocal','endsVowel','flat',14],
    ['cierre_duro','Cierre duro','common','Termina en consonante','endsConsonant','flat',12],
    ['cinco','Quinta esencia','common','Palabras de 5 letras','len5','flat',20],
    ['seis','Media docena','common','Palabras de 6 letras','len6','flat',28],
    ['siete','Siete magnífico','uncommon','Palabras de 7 letras','len7','flat',42],
    ['ocho','Octava mayor','rare','Palabras de 8 letras','len8','flat',58],
    ['larga','Largo recorrido','common','7 letras o más','min7','mult',1.3],
    ['mini','Precisión','common','Exactamente 3 letras','len3','flat',14],
    ['tilde','Acento agudo','uncommon','Contiene tilde o diéresis','accent','mult',1.55],
    ['ene','La letra española','rare','Contiene Ñ','ntilde','flat',45],
    ['sin_a','Sin A','uncommon','No contiene A','noA','mult',1.45],
    ['sin_e','Sin E','uncommon','No contiene E','noE','mult',1.4],
    ['sin_o','Sin O','uncommon','No contiene O','noO','mult',1.35],
    ['diversidad','Coleccionista','common','Cada letra distinta','always','uniqueFlat',2],
    ['repeticion','Eco léxico','uncommon','Por cada letra repetida','always','repeatFlat',8],
    ['raras','Cazador de rarezas','uncommon','J, Ñ, Q, X, Z, K o W','rareLetter','rareFlat',10],
    ['jota','J de jackpot','rare','Contiene J','containsJ','mult',1.7],
    ['zeta','Última letra','rare','Contiene Z','containsZ','mult',1.8],
    ['equis','Factor X','rare','Contiene X','containsX','flat',48],
    ['cu','Q de calidad','uncommon','Contiene Q','containsQ','flat',34],
    ['doble_vocal','Doble vocal','uncommon','Dos vocales seguidas','doubleVowel','flat',32],
    ['doble_consonante','Muro consonántico','uncommon','Tres consonantes seguidas','tripleConsonant','flat',38],
    ['escalera','Escalera','rare','Más larga que la anterior','longerThanPrev','mult',1.45],
    ['descenso','Contracorriente','uncommon','Más corta que la anterior','shorterThanPrev','flat',25],
    ['racha3','En racha','uncommon','3 aciertos seguidos o más','streak3','mult',1.3],
    ['racha5','Imparable','epic','5 aciertos seguidos o más','streak5','mult',1.65],
    ['primera','Primer golpe','common','Primera palabra de la ronda','firstPlay','flat',25],
    ['ultima','Último recurso','uncommon','Última jugada disponible','lastPlay','mult',1.5],
    ['par','Par perfecto','common','Longitud par','evenLength','flat',18],
    ['impar','Impar','common','Longitud impar','oddLength','flat',16],
    ['dos_a','A por partida doble','uncommon','Dos A o más','twoA','flat',28],
    ['dos_e','Energía E','uncommon','Dos E o más','twoE','flat',28],
    ['vocales3','Trío vocálico','rare','Tres vocales o más','threeVowels','mult',1.4],
    ['consonantes5','Fortaleza','rare','Cinco consonantes o más','fiveConsonants','mult',1.45],
    ['sin_repetir','Pieza única','rare','Ninguna letra repetida','allUnique','mult',1.5],
    ['palindromo','Espejo','legendary','Palíndromo de 3+ letras','palindrome','mult',3],
    ['inicio_m','M de maestro','common','Empieza por M','startsM','flat',18],
    ['inicio_p','P de palabra','common','Empieza por P','startsP','flat',18],
    ['final_s','Pluralista','common','Termina en S','endsS','flat',15],
    ['final_n','N final','common','Termina en N','endsN','flat',15],
    ['vocal_inicio_fin','Arco vocálico','rare','Empieza y termina por vocal','vowelEdges','mult',1.55],
    ['misma_punta','Simetría','epic','Misma letra al principio y al final','sameEdges','mult',1.8],
    ['alfabeto','Alfabético','epic','6+ letras distintas','sixUnique','flat',65],
    ['economia','Economía verbal','rare','4 letras o menos','max4','mult',1.7],
    ['decena','Decatlón','epic','10 letras o más','min10','mult',1.9],
    ['perfecta','Palabra perfecta','legendary','8+ letras y sin repetir letras','perfectWord','mult',2.2],
    ['acentuada_larga','Orfebrería','epic','7+ letras con tilde','accentLong','mult',1.85],
    ['rare_combo','Colección exótica','legendary','Dos letras raras o más','twoRare','mult',2.1],
    ['alquimista','Alquimista','rare','Cada ficha especial suma +16','specialTile','specialFlat',16],
    ['joyero','Joyero','epic','Dos fichas especiales o más','twoSpecialTiles','mult',1.65],
    ['cazajefes','Cazajefes','rare','Durante una ronda jefe','bossRound','mult',1.35],
    ['ortografo','Ortógrafo','epic','Tilde y letra rara en la misma palabra','accentAndRare','mult',1.75],
    ['cuatro_vocales','Coro vocálico','rare','Cuatro vocales o más','fourVowels','mult',1.45],
    ['sello_real','Sello real','legendary','Usa una ficha corona','crownTile','mult',1.8],
    ['nueve','Todo o nada','epic','Palabras de 9 letras o más','min9','mult',1.75],
    ['triple_rara','Trinidad exótica','legendary','Tres letras raras o más','threeRare','mult',2.4],
    ['doble_especial','Doble carga','uncommon','Dos fichas especiales o más','twoSpecialTiles','flat',50],
    ['sin_vocal_repetida','Vocales limpias','rare','No repite ninguna vocal','uniqueVowels','mult',1.4]
  ].map(([id,name,rarity,desc,condition,effect,value])=>({id,name,rarity,desc,condition,effect,value,type:'modifier'}));

  const gifts = [
    {id:'extra_play',name:'Segundo intento',rarity:'common',desc:'+1 jugada permanente por ronda.',type:'gift',effect:'extraPlay',value:1},
    {id:'extra_shuffle',name:'Mano nueva',rarity:'common',desc:'+1 barajado permanente por ronda.',type:'gift',effect:'extraShuffle',value:1},
    {id:'reroll',name:'Cambio de planes',rarity:'common',desc:'+1 reroll de recompensas.',type:'gift',effect:'reroll',value:1},
    {id:'length_up',name:'Amante de lo largo',rarity:'rare',desc:'+25% a todas las bonificaciones de longitud.',type:'gift',effect:'lengthMult',value:.25},
    {id:'letters_up',name:'Tipografía premium',rarity:'rare',desc:'+20% al valor base de todas las letras.',type:'gift',effect:'letterMult',value:.2},
    {id:'start_bonus',name:'Salida lanzada',rarity:'uncommon',desc:'+30 puntos al empezar cada ronda.',type:'gift',effect:'roundSeed',value:30},
    {id:'gold_tile',name:'Ficha dorada',rarity:'uncommon',desc:'Convierte una ficha aleatoria en dorada (×2).',type:'tile',effect:'gold'},
    {id:'diamond_tile',name:'Ficha diamante',rarity:'rare',desc:'Convierte una ficha aleatoria en diamante (×3).',type:'tile',effect:'diamond'},
    {id:'echo_tile',name:'Ficha eco',rarity:'rare',desc:'Una ficha suma dos veces su valor.',type:'tile',effect:'echo'},
    {id:'ink_tile',name:'Ficha tinta',rarity:'uncommon',desc:'Gana +1 de valor cada vez que se usa.',type:'tile',effect:'ink'},
    {id:'crown_tile',name:'Ficha corona',rarity:'epic',desc:'Esta ficha añade +25 al jugarla.',type:'tile',effect:'crown'},
    {id:'volatile_tile',name:'Ficha explosiva',rarity:'epic',desc:'Si se usa, multiplica ×1,35 la palabra.',type:'tile',effect:'volatile'},
    {id:'heal_shuffle',name:'Reorganización',rarity:'common',desc:'Recupera 2 barajados inmediatamente.',type:'gift',effect:'instantShuffle',value:2},
    {id:'heal_play',name:'Prórroga',rarity:'rare',desc:'Gana 1 jugada extra ahora y en esta ronda.',type:'gift',effect:'instantPlay',value:1},
    {id:'score_seed',name:'Fondo de puntos',rarity:'uncommon',desc:'+60 puntos inmediatos en la siguiente ronda.',type:'gift',effect:'nextRoundSeed',value:60},
    {id:'lexical_xp',name:'Biblioteca privada',rarity:'rare',desc:'+40 XP léxico al terminar la partida.',type:'gift',effect:'careerXp',value:40},
    {id:'boss_play',name:'Salvoconducto',rarity:'rare',desc:'+1 jugada extra en cada ronda jefe.',type:'gift',effect:'bossPlay',value:1},
    {id:'rare_luck',name:'Ojo del coleccionista',rarity:'epic',desc:'Mejora las probabilidades de recompensas raras.',type:'gift',effect:'rareLuck',value:1}
  ];

  const challenges = [
    {id:'none',title:'Ronda abierta',desc:'Cualquier palabra válida puntúa.',kind:'normal',targetMult:1},
    {id:'min5',title:'Palabra larga',desc:'Solo cuentan palabras de 5 letras o más.',kind:'constraint',targetMult:.96},
    {id:'vowel',title:'Puerta vocálica',desc:'La palabra debe empezar por vocal.',kind:'constraint',targetMult:.96},
    {id:'consonant',title:'Golpe consonante',desc:'La palabra debe empezar por consonante.',kind:'constraint',targetMult:.96},
    {id:'noA',title:'La A prohibida',desc:'No puedes usar la letra A.',kind:'constraint',targetMult:.94},
    {id:'unique',title:'Sin repetir',desc:'No puedes repetir ninguna letra.',kind:'constraint',targetMult:.94},
    {id:'exact5',title:'Cinco exactas',desc:'Solo palabras de exactamente 5 letras.',kind:'constraint',targetMult:.92},
    {id:'endsS',title:'Final en S',desc:'La palabra debe terminar en S.',kind:'constraint',targetMult:.93},
    {id:'twoVowels',title:'Vocal doble',desc:'Debe contener al menos dos vocales.',kind:'constraint',targetMult:.96},

    {id:'min6',title:'El Devorasílabas',desc:'JEFE · Solo acepta palabras de 6 letras o más.',kind:'boss',targetMult:.84,rewardTier:'rare'},
    {id:'noE',title:'La Reina Ausente',desc:'JEFE · No puedes utilizar la letra E.',kind:'boss',targetMult:.88,rewardTier:'rare'},
    {id:'accent',title:'El Inquisidor de Tildes',desc:'JEFE · Toda palabra debe contener tilde o diéresis.',kind:'boss',targetMult:.78,rewardTier:'rare'},
    {id:'ntilde',title:'El Guardián de la Ñ',desc:'JEFE · Toda palabra debe contener Ñ. El tablero te concederá una.',kind:'boss',targetMult:.76,rewardTier:'epic',setup:'ntilde'},
    {id:'exact6',title:'El Hexámetro',desc:'JEFE · Solo acepta palabras de exactamente 6 letras.',kind:'boss',targetMult:.80,rewardTier:'rare'},
    {id:'rare',title:'El Coleccionista Imposible',desc:'JEFE · Debes usar J, Ñ, Q, X o Z.',kind:'boss',targetMult:.80,rewardTier:'epic',setup:'rare'},
    {id:'threeVowels',title:'La Hidra Vocálica',desc:'JEFE · Cada palabra necesita al menos tres vocales.',kind:'boss',targetMult:.84,rewardTier:'rare',setup:'vowels'},
    {id:'longAccent',title:'El Maestro Ortográfico',desc:'JEFE · 6+ letras y al menos una tilde.',kind:'boss',targetMult:.72,rewardTier:'epic',setup:'vowels'},
    {id:'noCommon',title:'El Vacío',desc:'JEFE · No puedes utilizar A ni E.',kind:'boss',targetMult:.76,rewardTier:'epic',setup:'noCommon'}
  ];

  const achievements = [
    ['first','Primera palabra','Juega tu primera palabra.','careerWords',1],
    ['hundred','Centenario','Consigue 100 puntos en una sola palabra.','bestPlay',100],
    ['three_hundred','Tricentenario','Consigue 300 puntos en una sola palabra.','bestPlay',300],
    ['thousand','Rompe el marcador','Supera 1000 puntos totales en una partida.','runScore',1000],
    ['five_thousand','Fuera de escala','Supera 5000 puntos en una partida.','runScore',5000],
    ['long8','Académico','Forma una palabra de 8 letras.','longest',8],
    ['long10','Diccionario andante','Forma una palabra de 10 letras.','longest',10],
    ['ntilde','Ñandú','Juega una palabra con Ñ.','ntilde',1],
    ['accent','Bien acentuado','Juega una palabra con tilde.','accent',1],
    ['streak5','Imparable','Encadena 5 palabras válidas.','streak',5],
    ['streak10','Sin fallo','Encadena 10 palabras válidas.','streak',10],
    ['rare','Coleccionista raro','Usa una letra de valor 7 o más.','rare',1],
    ['win','Primera victoria','Completa las 12 rondas.','wins',1],
    ['wins5','Veterano','Gana 5 partidas.','wins',5],
    ['words100','Lector','Descubre 100 palabras distintas.','uniqueWords',100],
    ['words500','Lexicógrafo','Descubre 500 palabras distintas.','uniqueWords',500],
    ['cards10','Constructor','Descubre 10 cartas distintas.','cards',10],
    ['cards30','Maestro de combos','Descubre 30 cartas distintas.','cards',30],
    ['combo2','Sinergia','Alcanza un multiplicador ×2.','combo',2],
    ['combo4','Reacción en cadena','Alcanza un multiplicador ×4.','combo',4],
    ['quick','Velocista','Termina una partida rápida.','quick',1],
    ['daily','Rutina léxica','Completa un reto del día.','daily',1],
    ['perfect','Perfecto','Termina una partida sin errores de palabra.','perfect',1],
    ['allround','Doce estaciones','Llega a la ronda 12.','round',12]
  ].map(([id,name,desc,metric,value])=>({id,name,desc,metric,value}));

  return {modifiers,gifts,challenges,achievements};
})();
