(() => {
'use strict';
const params=new URLSearchParams(location.search),channel=params.get('channel')||'',embedded=params.get('lenguarcade')==='1',gameId='sopa_de_tinta';
if(!embedded||!channel)return;
let initialized=false,sourceWindow=null,pending=null,lastSignature='',exiting=false,exitId='',exitTimer=null;
const post=(type,payload={})=>{const message={namespace:'lenguarcade-game',channel,gameId,type,payload};if(sourceWindow){sourceWindow.postMessage(message,'*');return;}let w=window;for(let n=0;n<5;n++){if(w.parent===w)break;w=w.parent;w.postMessage(message,'*');}};
function metrics(){const r=TintaGame.run,n=r?.words.filter(w=>w.found).length||0,e=r?.errors||0;return {correct:n,errors:e,attempts:n+e,accuracy:n+e?Math.round(n/(n+e)*100):0,score:r?.score||0,maxCombo:r?.bestCombo||0,percentage:r?Math.round(n/r.words.length*100):0,time:r?.elapsed||0,hints:r?.hints||0,mode:r?.mode||'menu',category:r?.category||'all'};}
function player(result=false){const m=metrics();return {role:'primary',outcome:result?(TintaGame.run.won?'victory':'finished'):'checkpoint',score:result?m.score:0,correct:result?m.correct:0,errors:result?m.errors:0,maxCombo:m.maxCombo,accuracy:m.accuracy,attempts:result?m.attempts:0,grade:m.accuracy/10,percentage:m.percentage,metrics:m,achievements:TintaProgress.achievements.filter(a=>TintaGame.profile.achievements[a.id]).map(a=>({id:a.id,title:a.name,description:a.desc,xpReward:0})),save:TintaGame.package()};}
function checkpoint(reason='autosave'){if(!initialized)return '';TintaGame.save();const signature=JSON.stringify(TintaGame.package());if(reason==='autosave'&&lastSignature===signature)return '';lastSignature=signature;const id=gameId+'_checkpoint_'+crypto.randomUUID();post('CHECKPOINT',{checkpointId:id,matchId:TintaGame.run?.id||gameId+'_career',reason,players:[player()]});return id;}
function result(){if(!initialized||!TintaGame.run?.done)return;pending={resultId:gameId+'_result_'+TintaGame.run.id,matchId:TintaGame.run.id,outcome:TintaGame.run.won?'victory':'finished',players:[player(true)]};post('RESULT',pending);}
function finishExit(saved){clearTimeout(exitTimer);post('CLOSE_READY',{saved,checkpointId:exitId,localFallback:!saved});exiting=false;}
function saveAndExit(){if(exiting)return;exiting=true;TintaGame.freeze();TintaGame.save();exitId=checkpoint('exit');exitTimer=setTimeout(()=>finishExit(false),3000);}
function init(payload){if(initialized){post('INITIALIZED',{});return;}TintaGame.setContext(payload.student||{},payload.save||null);initialized=true;post('INITIALIZED',{restored:!!payload.save,profileId:payload.student?.studentId||''});if(TintaGame.run?.done)result();}
window.addEventListener('message',e=>{const m=e.data;if(!m||m.namespace!=='lenguarcade-host'||m.channel!==channel)return;let w=window,allowed=false;for(let n=0;n<5;n++){if(w.parent===w)break;w=w.parent;if(e.source===w){allowed=true;break;}}if(!allowed)return;if(m.type==='INIT'){sourceWindow=e.source;init(m.payload||{});}if(!initialized)return;if(m.type==='REQUEST_CHECKPOINT')checkpoint('host_request');if(m.type==='REQUEST_EXIT')saveAndExit();if(m.type==='SAVE_CONFIRMED'){pending=null;document.getElementById('save-status').textContent='Sincronizado';}if(m.type==='SAVE_FAILED'){document.getElementById('save-status').textContent='Pendiente de sincronizar';}if(m.type==='CHECKPOINT_CONFIRMED'){document.getElementById('save-status').textContent='Sincronizado';if(exiting&&m.payload?.checkpointId===exitId)finishExit(true);}if(m.type==='CHECKPOINT_FAILED'){lastSignature='';document.getElementById('save-status').textContent='Pendiente de sincronizar';if(exiting&&m.payload?.checkpointId===exitId)finishExit(false);}});
window.TintaBridge={checkpoint,result,saveAndExit,session:()=>{if(initialized)post('SESSION_STARTED',{mode:TintaGame.run?.mode});}};
try{const b=JSON.parse(window.name||'null');if(b?.namespace==='lenguarcade-bootstrap'&&b.channel===channel&&b.gameId===gameId){window.name='';init(b.payload||{});}}catch{}
const readyTimer=setInterval(()=>{if(initialized){clearInterval(readyTimer);return;}post('READY',{version:1});},900);post('READY',{version:1});
setInterval(()=>{if(pending)post('RESULT',pending);else checkpoint();},15000);
window.addEventListener('pagehide',()=>checkpoint('pagehide'));document.addEventListener('visibilitychange',()=>{if(document.hidden)checkpoint('hidden');});
})();
