(() => {
'use strict';
const C=TintaContent,G=TintaGenerator,P=TintaProgress,$=id=>document.getElementById(id),embedded=new URLSearchParams(location.search).get('lenguarcade')==='1';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const colors=['#6cd8bd','#ba9dff','#ffa997','#7acfff','#f1d577','#ec91c8','#91bbfa','#b4e989','#e9b97c','#9ededa','#ddb1ec'];
let profile=P.fresh(),run=null,storageKey='sopa_de_tinta:guest:v1',ready=!embedded,screen='home',selected=0,startCell=null,selection=[],pointerId=null,lastTick=Date.now(),toastTimer;
const concept=id=>C.concepts.find(c=>c.id===id),fmt=n=>Number(n||0).toLocaleString('es-ES'),time=n=>Math.floor(n/60).toString().padStart(2,'0')+':'+(n%60).toString().padStart(2,'0');
function icon(i=0){const paths=['M8 5h16v10c0 10-16 10-16 0zM24 7h3c7 0 7 9-3 9M5 29h23','M16 3l4 8 9 2-7 6 2 10-8-5-8 5 2-10-7-6 9-2z','M7 4h18v24H7zM12 10h8M12 16h8M12 22h5','M16 3l12 13-12 13L4 16zM16 9v14M9 16h14','M5 25l21-21M6 26l7-2-5-5zM20 5l7 7','M7 4h18v13c0 10-18 10-18 0zM12 12l4 4 7-7'];return `<svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="${paths[i%6]}"/></svg>`;}
function save(){profile.updatedAt=Date.now();try{localStorage.setItem(storageKey,JSON.stringify({version:1,profile,run}));$('save-status').textContent=embedded?'Guardado local':'Guardado';}catch{$('save-status').textContent='Guardado local no disponible';}header();}
function restoreDiscoveries(){profile.discovered||={};for(const [id,m] of Object.entries(profile.mastery||{}))if(m.clean>0&&!profile.discovered[id])profile.discovered[id]={count:m.clean,firstDay:''};for(const w of run?.words||[])if(w.found&&!profile.discovered[w.id])profile.discovered[w.id]={count:1,firstDay:run.day||''};}
function load(){try{const s=JSON.parse(localStorage.getItem(storageKey));if(s?.version===1&&s.profile){profile={...P.fresh(),...s.profile};run=s.run||null;}}catch{}restoreDiscoveries();P.missions(profile);}
function setContext(student,incoming){storageKey='sopa_de_tinta:'+encodeURIComponent(student?.studentId||student?.email||'embedded')+':v1';profile=P.fresh();run=null;load();const raw=incoming?.rawGameData?.save||incoming?.rawGameData||incoming?.save||incoming;
if(raw?.version===1&&raw.profile&&(!profile.updatedAt||(raw.profile.updatedAt||0)>=profile.updatedAt)){profile={...P.fresh(),...raw.profile};run=raw.run||null;}restoreDiscoveries();ready=true;save();home();}
function header(){const l=P.level(profile),from=100*(l-1)**2,to=100*l*l;$('level').textContent='Nv. '+l;$('xp').style.width=(profile.xp-from)/(to-from)*100+'%';$('xp').parentNode.title=`${profile.xp-from} / ${to-from} XP`;$('ink').textContent=fmt(profile.ink)+' Tintas';document.body.dataset.theme=profile.equipped.theme||'cafe';document.body.classList.toggle('reduced',profile.settings.reduced);document.body.classList.toggle('contrast',profile.settings.contrast);document.body.classList.toggle('gold',profile.equipped.frame==='oro');document.body.style.setProperty('--selection',profile.equipped.trace==='rosa'?'#f0a1d6':profile.equipped.trace==='menta'?'#85ebbd':'#90e8d7');}
function toast(text,type='correct'){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').className='show';TintaAudio.play(type);toastTimer=setTimeout(()=>$('toast').className='',2800);}
function checkAchievements(){for(const a of P.unlock(profile))setTimeout(()=>toast('Logro desbloqueado · '+a.name,'achievement'),100);}
function dialog(html){$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
function home(){screen='home';startCell=null;header();const discoveries=Object.keys(profile.discovered||{}).length;$('screen').innerHTML=`<section class="home"><div class="intro"><span class="eyebrow"><i class="live-dot"></i> CAFÉ ABIERTO · TU AVENTURA EMPIEZA AQUÍ</span><h1>SOPA<br><span>DE TINTA</span></h1><div class="title-rule">EL CAFÉ DE LOS CONCEPTOS</div><p>Descifra los pedidos. Conecta las letras.<br>Conquista los siete distritos de la tinta.</p><div class="home-actions"><button class="primary launch" data-action="adventure"><span class="action-icon">${icon(4)}</span><span>JUGAR AVENTURA<small>7 distritos · 28 pedidos · Hora Punta</small></span><b>›</b></button><button data-action="quick">${icon(0)}<span>Partida rápida<small>Tu café, tus reglas</small></span></button><button data-action="daily">${icon(1)}<span>Desafío diario<small>Un nuevo pedido cada día</small></span></button></div><div class="links">${run&&!run.done?'<button data-action="resume">Continuar pedido</button>':''}<button data-action="glossary">${icon(2)} Glosario <b>${discoveries}/${C.concepts.length}</b></button><button data-action="achievements">${icon(5)} Logros</button><button data-action="stats">Estadísticas</button><button data-action="shop">Decora tu café</button></div></div><div class="cafe-scene"><div class="floating-tiles" aria-hidden="true"><i>T</i><i>I</i><i>N</i><i>T</i><i>A</i></div><div class="scene-tag">${icon(0)}<span>${P.level(profile)>=20?'Maestro de la Tinta':P.level(profile)>=15?'Lexicógrafo':P.level(profile)>=10?'Rastreador':P.level(profile)>=5?'Buscapalabras':'Aprendiz'}<small>${profile.streak} días de racha · ${fmt(profile.stats.words)} conceptos</small></span></div><button class="collection-link" data-action="glossary">${icon(2)}<span>Tu libro de descubrimientos<small>${discoveries} conceptos recuperados</small></span><b>›</b></button></div><div class="mission-bar"><span class="eyebrow">TABLÓN DE<br>ENCARGOS</span>${P.missions(profile).items.map(m=>{const v=Math.min(m.target,(profile.stats[m.id]||0)-(profile.missions.base[m.id]||0));return `<button data-action="claim" data-id="${m.id}" ${v<m.target||profile.missions.claimed.includes(m.id)?'disabled':''}><span>${m.name}</span><b>${profile.missions.claimed.includes(m.id)?'Cobrado':`${v}/${m.target}`}</b><small>+60 XP · +15 Tintas</small><div class="mission-fill"><i style="width:${v/m.target*100}%"></i></div></button>`;}).join('')}</div></section>`;}

function adventure(){screen='adventure';$('screen').innerHTML=`<section class="page adventure-page"><div class="page-title"><div><span class="eyebrow">TU RUTA POR LA CIUDAD</span><h2>Siete cafés. Una aventura.</h2><p class="adventure-help">Elige un distrito y pulsa Jugar.</p></div><button data-action="home">Volver</button></div><div class="districts">${C.districts.map((d,i)=>{const levels=profile.adventure[d.id]||{},pending=[0,1,2,3].find(stage=>!levels[stage]),next=pending??0;return `<article class="district" style="--district:${d.color}"><div class="district-heading">${icon(i)}<div><span class="eyebrow">DISTRITO ${i+1}</span><h3>${d.name}</h3></div></div><button class="primary district-play" type="button" data-action="stage" data-category="${d.id}" data-stage="${next}">JUGAR · ${next===3?'HORA PUNTA':'PEDIDO '+(next+1)} <span aria-hidden="true">›</span></button><div class="stages" aria-label="Pedidos de ${esc(d.name)}">${[0,1,2,3].map(stage=>{const locked=stage>0&&!levels[stage-1];return `<button type="button" data-action="stage" data-category="${d.id}" data-stage="${stage}" ${locked?'disabled':''}>${stage===3?'Hora Punta':'Pedido '+(stage+1)}<small>${levels[stage]?'★'.repeat(levels[stage]):locked?'Bloqueado':'Jugar'}</small></button>`;}).join('')}</div></article>`;}).join('')}</div></section>`;}
function quick(){dialog(`<span class="eyebrow">A TU GUSTO</span><h2>Prepara tu pedido</h2><label>Modo<select id="mode"><option value="relax">Relax · sin reloj</option><option value="timed">Contrarreloj · 180 s</option><option value="master">Maestría · conceptos difíciles</option></select></label><label>Dificultad<select id="difficulty">${C.difficulties.map((d,i)=>`<option value="${i}">${d.name} · ${d.size}×${d.size}</option>`).join('')}</select></label><label>Contenido<select id="category"><option value="all">Todas las categorías</option>${C.districts.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}</select></label><button class="primary" data-action="start-quick">Servir pedido</button>`);}
function requestStart(options){if(run&&!run.done){dialog(`<h2>Hay un pedido en marcha</h2><p>Puedes continuarlo o cerrar ese pedido y preparar el nuevo. Lo ya conseguido se conserva.</p><button data-action="resume">Continuar</button><button id="replace-run" class="primary">Cerrar pedido y empezar</button>`);$('replace-run').onclick=()=>{settle(false);start(options);};return;}start(options);}
function start({mode='relax',difficulty=1,category='all',stage=0}={}){if(!ready)return;if(mode==='master')difficulty=3;if(mode==='boss')difficulty=3;if(mode==='daily'){difficulty=2;category='all';}
const d=C.difficulties[difficulty],today=P.day(),seed=mode==='daily'?'sopa-de-tinta:v1:'+today:crypto.randomUUID();
try{const board=G.generate({seed,size:d.size,count:mode==='boss'?10:d.count,reverse:d.reverse,category,hard:mode==='master',mastery:mode==='daily'?{}:profile.mastery});run={version:1,id:crypto.randomUUID(),...board,mode,difficulty,category,stage,day:today,score:0,combo:0,bestCombo:0,errors:0,hints:0,elapsed:0,lastFound:0,limit:mode==='boss'?90:mode==='timed'?180:null,done:false,settled:false,reward:null};selected=0;lastTick=Date.now();$('modal').close();save();play();window.TintaBridge?.session();window.TintaBridge?.checkpoint('start');}catch(e){toast(e.message,'error');}}
function play(){if(!run)return;if(run.done){results();return;}screen='play';lastTick=Date.now();$('screen').innerHTML=`<section class="play"><div class="hud"><div><small>${run.mode==='boss'?'HORA PUNTA':{relax:'SOBREMESA',timed:'CONTRARRELOJ',master:'MAESTRÍA',daily:'PEDIDO DEL DÍA',adventure:'AVENTURA'}[run.mode]}</small><b id="score"></b></div><div><small>RACHA</small><b id="combo"></b></div><div><small>${run.mode==='relax'?'SIN PRISA':'TIEMPO'}</small><b id="clock"></b></div><div><small>FICHAS DE AYUDA</small><b id="tokens"></b></div><button data-action="pause">Pausa / Café</button></div><div class="play-body"><div class="board-area"><div class="board-label"><span>${esc(C.districts.find(d=>d.id===run.category)?.name||'Café de los conceptos')}</span><span>${C.difficulties[run.difficulty].name}</span></div><div class="board-slot"><div id="board" class="board" style="--n:${run.grid.length}" role="group" aria-label="Sopa de letras. Arrastra o usa el teclado para seleccionar las letras.">${run.grid.flatMap((row,r)=>row.map((ch,c)=>`<button class="cell" data-r="${r}" data-c="${c}" aria-label="Fila ${r+1}, columna ${c+1}, ${ch}">${ch}</button>`)).join('')}</div></div><div id="feedback" class="feedback" role="status">Deduce una definición. Arrastra desde la primera hasta la última letra.</div></div><aside><div class="orders-title"><div><span class="eyebrow">BARRA DE PEDIDOS</span><h2>¿Qué servimos?</h2></div><span id="count"></span></div><div id="clues" class="clues"></div><div class="hints"><button data-action="hint" data-kind="letter">Letra <small>1 ficha</small></button><button data-action="hint" data-kind="compass">Brújula <small>2 fichas</small></button><button data-action="hint" data-kind="magic">Tinta mágica <small>3 fichas</small></button></div></aside></div><footer><div class="progress-track"><i id="progress"></i></div><span id="service"></span></footer></section>`;
document.querySelector('.play').style.setProperty('--district',C.districts.find(d=>d.id===run.category)?.color||'#736183');const b=$('board');b.addEventListener('pointerdown',down);b.addEventListener('pointermove',move);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',cancel);b.addEventListener('keydown',keyboard);renderBoard();updateRun();}
function updateRun(){if(screen!=='play'||!run)return;$('score').textContent=fmt(run.score)+' pts';$('combo').textContent=run.combo+' · ×'+(1+Math.min(5,Math.max(0,run.combo-1))*.2).toFixed(1);$('clock').textContent=run.mode==='relax'?'∞':time(run.limit===null?run.elapsed:Math.max(0,run.limit-run.elapsed));$('tokens').textContent=profile.hintTokens;$('count').textContent=run.words.filter(w=>w.found).length+'/'+run.words.length;$('progress').style.width=run.words.filter(w=>w.found).length/run.words.length*100+'%';$('service').textContent=run.mode==='boss'?`Clientes atendidos ${run.words.filter(w=>w.found).length}/${run.words.length} · ${3-run.errors} errores restantes`:`${run.errors} errores · ${run.hints} ayudas`;
if(run.mode==='boss')$('service').innerHTML=`<span class="rush-meter" aria-label="Clientes esperando">${run.words.map(w=>`<svg class="patron ${w.found?'served':''}" viewBox="0 0 24 28" aria-hidden="true"><circle cx="12" cy="7" r="5"/><path d="M3 26v-7c0-9 18-9 18 0v7z"/></svg>`).join('')}</span> ${3-run.errors} errores restantes`;
$('clues').innerHTML=run.words.map((w,i)=>{const c=concept(w.id);return `<button class="clue ${w.found?'found':''} ${selected===i?'chosen':''}" data-action="choose" data-index="${i}" style="--word:${colors[i]}"><span class="clue-number">${w.found?'✓':String(i+1).padStart(2,'0')}</span><span>${w.found?`<strong>${esc(c.term)}</strong><small>${esc(c.explanation)}</small>`:`${esc(c.clue)}<small>${c.gridTerm.length} letras${w.letter?' · Empieza por '+c.gridTerm[0]:''}${w.compass?' · '+esc(w.compass):''}</small>`}</span></button>`;}).join('');}
function renderBoard(){if(!$('board'))return;const cells=$('board').children;for(const cell of cells){cell.className='cell';cell.style.removeProperty('--word');cell.removeAttribute('data-mark');}
run.words.forEach((w,i)=>{if(w.found)w.cells.forEach(([r,c])=>{const cell=cells[r*run.grid.length+c];cell.classList.add('solved');cell.style.setProperty('--word',colors[i]);cell.dataset.mark=String(i+1);});});for(const [r,c] of selection)cells[r*run.grid.length+c]?.classList.add('selecting');}
function cellAt(e){const rect=$('board').getBoundingClientRect(),r=Math.floor((e.clientY-rect.top)/rect.height*run.grid.length),c=Math.floor((e.clientX-rect.left)/rect.width*run.grid.length);return r<0||c<0||r>=run.grid.length||c>=run.grid.length?null:[r,c];}
function down(e){if(run.done||e.button!==0)return;startCell=cellAt(e);if(!startCell)return;pointerId=e.pointerId;$('board').setPointerCapture(e.pointerId);selection=[startCell];renderBoard();e.preventDefault();}
function move(e){if(pointerId!==e.pointerId||!startCell)return;const end=cellAt(e);if(!end)return;const p=G.path(startCell,end,run.grid.length);if(!p.length)return;if(p.length!==selection.length)TintaAudio.play('letter');selection=p;renderBoard();}
function up(e){if(e.pointerId!==pointerId)return;pointerId=null;startCell=null;submit(selection);selection=[];renderBoard();}
function cancel(){pointerId=null;startCell=null;selection=[];renderBoard();}
function keyboard(e){const cell=e.target.closest('.cell');if(!cell)return;let r=+cell.dataset.r,c=+cell.dataset.c;const changes={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(changes[e.key]){e.preventDefault();const [dr,dc]=changes[e.key];r=Math.max(0,Math.min(run.grid.length-1,r+dr));c=Math.max(0,Math.min(run.grid.length-1,c+dc));$('board').children[r*run.grid.length+c].focus();}if(e.key==='Enter'||e.key===' '){e.preventDefault();if(!startCell){startCell=[r,c];selection=[startCell];renderBoard();}else{const p=G.path(startCell,[r,c],run.grid.length);startCell=null;selection=[];submit(p);renderBoard();}}if(e.key==='Escape')cancel();}
function submit(cells){if(!run||run.done||screen!=='play'||cells.length<2)return false;const w=G.match(run.grid,cells,run.words);if(!w){run.errors++;P.add(profile,'errors');run.combo=0;$('board').classList.add('wrong');setTimeout(()=>$('board')?.classList.remove('wrong'),260);$('feedback').textContent='Esa selección no corresponde a un pedido. Revisa la definición.';TintaAudio.play('error');if(run.mode==='boss'&&run.errors>=3){settle(false);return false;}save();updateRun();return false;}
w.found=true;w.cells=cells.map(x=>[...x]);run.combo++;run.bestCombo=Math.max(run.bestCombo,run.combo);profile.stats.bestCombo=Math.max(profile.stats.bestCombo||0,run.bestCombo);const c=concept(w.id),points=P.score(c,run,w);profile.discovered||={};const discovered=profile.discovered[w.id]||={count:0,firstDay:P.day()};discovered.count++;run.score+=points;run.lastFound=run.elapsed;P.add(profile,'words');const dr=cells.at(-1)[0]-cells[0][0],dc=cells.at(-1)[1]-cells[0][1];P.add(profile,dr&&dc?'diagonal':dr?'vertical':'horizontal');if(dr<0||(dr===0&&dc<0))P.add(profile,'reverse');const mastery=profile.mastery[w.id]||={clean:0,help:0};mastery[w.hints?'help':'clean']++;$('feedback').textContent=c.explanation;toast(`+${points} · ${c.term} · Racha ${run.combo}`);selected=run.words.findIndex(x=>!x.found);checkAchievements();save();updateRun();renderBoard();celebrate(w,points);window.TintaBridge?.checkpoint('word');if(run.words.every(x=>x.found))settle(true);return true;}
function celebrate(w,points){const board=$('board');if(!board)return;board.classList.remove('word-pop');void board.offsetWidth;board.classList.add('word-pop');setTimeout(()=>board.classList.remove('word-pop'),450);if(profile.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const rect=board.getBoundingClientRect(),[r,c]=w.cells[Math.floor(w.cells.length/2)];const fx=document.createElement('div');fx.className='score-burst';fx.textContent='+'+points;fx.style.left=(rect.left+(c+.5)*rect.width/run.grid.length)+'px';fx.style.top=(rect.top+(r+.5)*rect.height/run.grid.length)+'px';document.body.append(fx);setTimeout(()=>fx.remove(),1000);}
function glossary(){screen='glossary';$('screen').innerHTML=`<section class="page glossary"><div class="page-title"><div><span class="eyebrow">EL LIBRO DE TUS DESCUBRIMIENTOS</span><h2>Glosario de tinta <small>${Object.keys(profile.discovered||{}).length} / ${C.concepts.length} conceptos encontrados</small></h2></div><button data-action="home">Volver al café</button></div><div class="glossary-tools"><label class="search-label">Buscar concepto<input id="glossary-search" type="search" placeholder="Palabra o definición…" autocomplete="off"></label><label>Tema<select id="glossary-category"><option value="all">Todos los distritos</option>${C.districts.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}</select></label><span id="glossary-count" role="status"></span></div><div id="glossary-cards" class="glossary-cards"></div></section>`;renderGlossary();$('glossary-search').addEventListener('input',renderGlossary);$('glossary-category').addEventListener('change',renderGlossary);}
function renderGlossary(){const fold=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es'),q=fold($('glossary-search').value.trim()),category=$('glossary-category').value;const found=C.concepts.filter(c=>profile.discovered?.[c.id]),list=found.filter(c=>(category==='all'||c.category===category)&&fold(c.term+' '+c.clue+' '+c.explanation).includes(q)).sort((a,b)=>a.term.localeCompare(b.term,'es'));$('glossary-count').textContent=list.length+' conceptos';$('glossary-cards').innerHTML=list.length?list.map(c=>{const d=C.districts.find(d=>d.id===c.category),entry=profile.discovered[c.id];return `<article class="glossary-card" style="--district:${d?.color||'#90e8d7'}"><div class="book-spine" aria-hidden="true">${icon(2)}</div><div><span class="eyebrow">${esc(d?.name||c.category)}</span><h3>${esc(c.term)}</h3><p>${esc(c.explanation)}</p>${c.clue!==c.explanation?`<blockquote>${esc(c.clue)}</blockquote>`:''}<small>ENCONTRADO ${entry.count||1} ${(entry.count||1)===1?'VEZ':'VECES'}${entry.firstDay?' · '+esc(entry.firstDay):''}</small></div></article>`;}).join(''):`<div class="empty-book">${icon(2)}<h3>${found.length?'No hay coincidencias':'Tu libro está por escribir'}</h3><p>${found.length?'Prueba otra palabra o cambia de distrito.':'Encuentra tu primer concepto: su definición quedará guardada aquí.'}</p>${!found.length?'<button class="primary" data-action="quick">Buscar mi primer concepto</button>':''}</div>`;}
function hint(kind){if(!run||run.done)return;const w=run.words[selected];if(!w||w.found){toast('Selecciona un pedido pendiente.','error');return;}if(run.mode==='master'&&w.hints>=1){toast('En Maestría hay una ayuda por concepto.','error');return;}const cost={letter:1,compass:2,magic:3}[kind];if(profile.hintTokens<cost){toast('Consigue más fichas completando pedidos.','error');return;}if(kind==='letter'&&w.letter||kind==='compass'&&w.compass){toast('Esta ayuda ya está visible.','error');return;}profile.hintTokens-=cost;run.hints++;w.hints++;run.combo=0;P.add(profile,'hints');if(kind==='letter')w.letter=true;if(kind==='compass'){const [r,c]=w.cells[0];w.compass=(r<run.grid.length/2?'Zona superior':'Zona inferior')+', '+(c<run.grid.length/2?'izquierda':'derecha');}if(kind==='magic'){w.cells.slice(0,Math.ceil(w.cells.length/2)).forEach(([r,c])=>$('board').children[r*run.grid.length+c].classList.add('magic'));setTimeout(()=>{if(screen==='play')renderBoard();},3000);}save();updateRun();window.TintaBridge?.checkpoint('hint');}
function settle(won){P.finish(profile,run,won);checkAchievements();save();window.TintaBridge?.result();results();}
function results(){screen='results';const reward=run.reward||{},found=run.words.filter(w=>w.found),review=run.words.filter(w=>!w.found||w.hints);$('screen').innerHTML=`<section class="results"><span class="eyebrow">${reward.isRecord?'NUEVO RÉCORD':run.mode==='boss'?'HORA PUNTA':'PEDIDO FINALIZADO'}</span><h1>${run.won?'Sopa completada':'El café sigue abierto'}</h1><div class="stars" aria-label="${reward.stars||0} estrellas">${'★'.repeat(reward.stars||0)}${'☆'.repeat(3-(reward.stars||0))}</div><div class="result-score">${fmt(run.score)}<small>puntos</small></div><div class="result-metrics"><span>Precisión<b>${Math.round(found.length/Math.max(1,found.length+run.errors)*100)} %</b></span><span>Tiempo<b>${time(run.elapsed)}</b></span><span>Mejor racha<b>${run.bestCombo}</b></span><span>Pistas<b>${run.hints}</b></span></div><div class="reward">+${reward.xp||0} XP · +${reward.ink||0} Tintas ${reward.levelUp?'· ¡SUBES DE NIVEL!':''}${reward.bonus?' · +'+reward.bonus+' bonus':''}</div><div class="learning"><div><h3>Recuperados sin ayuda</h3><p>${found.filter(w=>!w.hints).map(w=>esc(concept(w.id).term)).join(' · ')||'Sigue practicando: cada pedido cuenta.'}</p></div><div><h3>Conviene repasar</h3><p>${review.map(w=>esc(concept(w.id).term)).join(' · ')||'¡Todos los conceptos resueltos sin ayuda!'}</p></div></div><div class="result-actions"><button data-action="home">Volver al café</button><button class="primary" data-action="again">Otro pedido</button><button data-action="glossary">Abrir glosario</button>${run.mode==='adventure'||run.mode==='boss'?'<button data-action="adventure">Ver distritos</button>':''}</div></section>`;TintaAudio.play('finish');}
function achievements(){screen='achievements';$('screen').innerHTML=`<section class="page"><div class="page-title"><h2>La colección · ${Object.keys(profile.achievements).length}/37</h2><button data-action="home">Volver</button></div><div class="collection">${P.achievements.map(a=>`<article class="achievement ${profile.achievements[a.id]?'unlocked':''}">${icon(a.icon)}<div><h3>${a.name}</h3><p>${a.desc}</p><small>${profile.achievements[a.id]?'Desbloqueado · '+profile.achievements[a.id]:'+20 XP'}</small></div></article>`).join('')}</div></section>`;}
function stats(){screen='stats';const s=profile.stats,total=(s.words||0)+(s.errors||0),category=C.districts.map(d=>[d, Object.entries(profile.mastery).filter(([id])=>concept(id)?.category===d.id).reduce((sum,[,m])=>sum+m.clean+m.help,0)]).sort((a,b)=>b[1]-a[1]);$('screen').innerHTML=`<section class="page"><div class="page-title"><h2>Tu historia en tinta</h2><button data-action="home">Volver</button></div><div class="stats-grid">${[['Pedidos jugados',s.played],['Completados',s.wins],['Conceptos',s.words],['Errores',s.errors],['Precisión',Math.round((s.words||0)/Math.max(1,total)*100)+' %'],['Mejor racha',s.bestCombo],['Ayudas',s.hints],['Horizontales',s.horizontal],['Verticales',s.vertical],['Diagonales',s.diagonal],['Invertidas',s.reverse],['Perfectos',s.perfects],['Horas punta',s.bossWins],['Puntos totales',s.totalScore],['Categoría más practicada',category[0][1]?category[0][0].name:'—'],['Mejor tiempo',Object.keys(profile.records).length?time(Math.min(...Object.values(profile.records).map(r=>r.time))):'—']].map(([name,v])=>`<article><small>${name}</small><b>${typeof v==='number'?fmt(v):v||0}</b></article>`).join('')}</div><h3>Últimos pedidos diarios · registros personales</h3><div class="daily-records">${Object.entries(profile.daily).slice(-7).map(([date,r])=>`<p>${date} · ${fmt(r.score)} pts · ${time(r.time)} · ${r.errors} errores · ${r.hints} ayudas</p>`).join('')||'<p>Todavía no has completado un pedido diario.</p>'}</div></section>`;}
function shop(){screen='shop';$('screen').innerHTML=`<section class="page"><div class="page-title"><div><span class="eyebrow">SOLO PERSONALIZACIÓN</span><h2>Tu rincón · ${fmt(profile.ink)} Tintas</h2></div><button data-action="home">Volver</button></div><div class="shop-grid">${P.cosmetics.map((c,i)=>`<article class="cosmetic">${icon(i)}<h3>${c.name}</h3><button data-action="buy" data-id="${c.id}" ${!profile.owned.includes(c.id)&&profile.ink<c.cost?'disabled':''}>${profile.equipped[c.kind]===c.id?'Equipado':profile.owned.includes(c.id)?'Equipar':c.cost+' Tintas'}</button></article>`).join('')}</div></section>`;}
function settings(){dialog(`<h2>Ajustes del café</h2>${[['sound','Efectos de sonido'],['music','Música suave'],['reduced','Reducir animaciones'],['contrast','Alto contraste']].map(([id,label])=>`<label class="toggle"><span>${label}</span><input type="checkbox" data-setting="${id}" ${profile.settings[id]?'checked':''}></label>`).join('')}<p class="sub">También puedes seleccionar con teclado: flechas para moverte; Intro en la primera y en la última letra.</p>`);}
function pause(){screen='home';$('modal').close();save();window.TintaBridge?.checkpoint('pause');home();}
function act(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;if(action==='home')home();if(action==='adventure')adventure();if(action==='quick')quick();if(action==='resume'){$('modal').close();play();}if(action==='daily')requestStart({mode:'daily'});if(action==='stage'){const stage=+b.dataset.stage;requestStart({mode:stage===3?'boss':'adventure',difficulty:stage,category:b.dataset.category,stage});}if(action==='start-quick')requestStart({mode:$('mode').value,difficulty:+$('difficulty').value,category:$('category').value});if(action==='pause')pause();if(action==='achievements')achievements();if(action==='stats')stats();if(action==='glossary')glossary();if(action==='shop')shop();if(action==='choose'){selected=+b.dataset.index;updateRun();}if(action==='hint')hint(b.dataset.kind);if(action==='claim'){if(P.claim(profile,b.dataset.id)){checkAchievements();save();home();toast('Encargo cumplido · +60 XP · +15 Tintas');window.TintaBridge?.checkpoint('mission');}}if(action==='buy'){const c=P.cosmetics.find(x=>x.id===b.dataset.id);if(!profile.owned.includes(c.id)){if(profile.ink<c.cost)return;profile.ink-=c.cost;profile.owned.push(c.id);P.add(profile,'purchases');}profile.equipped[c.kind]=c.id;checkAchievements();save();shop();window.TintaBridge?.checkpoint('cosmetic');}if(action==='again')requestStart({mode:run.mode,difficulty:run.difficulty,category:run.category,stage:run.stage});}
document.addEventListener('click',act);document.addEventListener('change',e=>{const key=e.target.dataset.setting;if(key){profile.settings[key]=e.target.checked;save();TintaAudio.music();window.TintaBridge?.checkpoint('settings');}});$('settings').onclick=settings;$('close-modal').onclick=()=>$('modal').close();document.querySelector('.brand').onclick=e=>{e.preventDefault();pause();};$('exit').onclick=pause;
setInterval(()=>{const now=Date.now();if(screen==='play'&&run&&!run.done){const secs=Math.floor((now-lastTick)/1000);if(secs>0){run.elapsed+=secs;lastTick+=secs*1000;updateClock();if(run.limit&&run.elapsed>=run.limit)settle(false);}}else lastTick=now;},250);
function updateClock(){if($('clock'))$('clock').textContent=run.mode==='relax'?'∞':time(run.limit===null?run.elapsed:Math.max(0,run.limit-run.elapsed));}
setInterval(()=>{if(ready&&run&&!run.done&&screen==='play')save();},10000);window.addEventListener('pagehide',()=>{if(ready)save();});
window.TintaGame={get profile(){return profile;},get run(){return run;},get ready(){return ready;},setContext,save,submit,start,play,home,package:()=>({version:1,profile,run}),getScreen:()=>screen,freeze:()=>{screen='exit';cancel();},icon};
if(ready){load();home();}else $('screen').innerHTML='<section class="results"><h2>Abriendo el café…</h2><p>Esperando tu perfil de LenguArcade.</p></section>';
})();
