(function(){
"use strict";
var GAME_ID="versopolis",GAME_NS="lenguarcade-game",HOST_NS="lenguarcade-host";
var params=Object.fromEntries(new URLSearchParams(location.search||"").entries()),embedded=String(params.lenguarcade||params.la||"")==="1",channel=String(params.channel||"");
var initialized=false,profile=null,lastSig="",timer=null,lastResult=false,exitRequested=false,exitCheckpointId="",exitTimer=null,started=false;
if(!embedded||!channel)return;window.__LENGUARCADE_EMBEDDED=true;
function postToAncestors(message){var target=window;for(var depth=0;depth<5;depth+=1){try{if(!target.parent||target.parent===target)break;target=target.parent;target.postMessage(message,"*");}catch(err){break;}}}
function post(type,payload){postToAncestors({namespace:GAME_NS,channel:channel,gameId:GAME_ID,type:type,payload:payload||{}});}
function metrics(){return window.VersopolisGame&&window.VersopolisGame.metrics?window.VersopolisGame.metrics():{score:0,attempts:0,correct:0,errors:0,accuracy:0,percentage:0};}
function participant(outcome){var m=metrics();return{role:"primary",outcome:outcome||"checkpoint",score:m.score,correct:m.correct,errors:m.errors,attempts:m.attempts,accuracy:m.accuracy,grade:Math.round(m.accuracy)/10,percentage:m.percentage,maxCombo:m.bestStreak,metrics:m,save:window.VersopolisGame&&window.VersopolisGame.snapshot?window.VersopolisGame.snapshot():null};}
function safeId(v){return String(v||"player").toLowerCase().replace(/[^a-z0-9_-]+/g,"_").slice(0,48)||"player";}
function checkpoint(reason){if(!initialized)return"";var m=metrics(),sig=[m.score,m.attempts,m.correct,m.percentage,m.bestStreak].join("|");if((reason||"autosave")==="autosave"&&sig===lastSig)return"";lastSig=sig;var id="versopolis_checkpoint_"+Date.now()+"_"+Math.random().toString(36).slice(2);post("CHECKPOINT",{checkpointId:id,matchId:"versopolis_"+safeId(profile&&(profile.studentId||profile.email)),reason:reason||"autosave",players:[participant("checkpoint")]});return id;}
function result(outcome){if(!initialized||lastResult)return;lastResult=true;post("RESULT",{resultId:"versopolis_result_"+Date.now()+"_"+Math.random().toString(36).slice(2),matchId:"versopolis_"+safeId(profile&&(profile.studentId||profile.email)),outcome:outcome||"finished",players:[participant(outcome||"finished")]});}
function finishExit(saved){if(!exitRequested)return;if(exitTimer){clearTimeout(exitTimer);exitTimer=null;}post("CLOSE_READY",{saved:saved!==false,checkpointId:exitCheckpointId,localFallback:saved===false});exitRequested=false;exitCheckpointId="";}
function saveAndExit(){if(exitRequested)return;exitRequested=true;exitCheckpointId=checkpoint("exit");if(!exitCheckpointId){finishExit(true);return;}exitTimer=setTimeout(function(){finishExit(false);},2500);}
function sessionStarted(){if(started)return;started=true;post("SESSION_STARTED",{mode:"duelo_lirico"});}
function restore(save){try{var raw=save&&save.rawGameData&&save.rawGameData.save?save.rawGameData.save:(save&&save.rawGameData?save.rawGameData:(save&&save.save?save.save:save));return !!(window.VersopolisGame&&window.VersopolisGame.restore&&window.VersopolisGame.restore(raw));}catch(err){return false;}}
window.addEventListener("message",function(event){var msg=event.data||{};if(msg.namespace!==HOST_NS||msg.channel!==channel)return;if(msg.type==="INIT"){profile=msg.payload&&msg.payload.student||{};var restored=restore(msg.payload&&msg.payload.save||null);initialized=true;post("INITIALIZED",{profileId:profile.studentId||profile.email||"",restored:restored});post("READY",{gameId:GAME_ID,version:1});if(!timer)timer=setInterval(function(){checkpoint("autosave");},15000);}if(msg.type==="REQUEST_CHECKPOINT")checkpoint("host_request");if(msg.type==="REQUEST_EXIT")saveAndExit();if(msg.type==="CHECKPOINT_CONFIRMED"&&exitRequested&&(!exitCheckpointId||msg.payload&&msg.payload.checkpointId===exitCheckpointId))finishExit(true);if(msg.type==="CHECKPOINT_FAILED"&&exitRequested&&(!exitCheckpointId||msg.payload&&msg.payload.checkpointId===exitCheckpointId))finishExit(false);});
window.addEventListener("pagehide",function(){if(!exitRequested)checkpoint("pagehide");});document.addEventListener("visibilitychange",function(){if(document.visibilityState==="hidden"&&!exitRequested)checkpoint("visibility_hidden");});
var readyTimer=setInterval(function(){if(initialized){clearInterval(readyTimer);return;}post("READY",{gameId:GAME_ID,version:1});},900);post("READY",{gameId:GAME_ID,version:1});
window.VersopolisBridge={checkpoint:checkpoint,result:result,saveAndExit:saveAndExit,sessionStarted:sessionStarted};
})();
