/* Controlled verse families: stable IDs, original text, natural subjects and
   compatible complements. Prosody supplies a consistent default reading. */
(function(){
'use strict';
var subjects=[['La noche','noche'],['La luna','noche'],['La sombra','noche'],['La tarde','tiempo'],['La brisa','paisaje'],['La lluvia','paisaje'],['La niebla','paisaje'],['La fuente','ciudad'],['La calle','ciudad'],['La plaza','ciudad'],['El bosque','paisaje'],['El río','paisaje']];
var families=[
 {verb:'guarda',objects:['mi canto','tu canto','su canto','mi llanto','tu llanto','el camino','mi destino','el molino','mi sueño','tu sueño','mi risa','tu risa','la prisa','la calma','mi alma','la fuente','la gente','el presente','el pasado','lo soñado','lo callado','cada día','la alegría','la casa','la rama','la plata','la mesa','la senda','la niebla','la cueva','la mañana','la ventana','la campana','el rumor','el temblor','el color','el fulgor','la flor','el mar','el hogar','el cristal','la canción','la ilusión','el son del molino','el son del camino','el son de la fuente','el son del presente','el son del pasado','el son del soldado','el son de la casa','el son de la rama','el son de la mesa','el son de la senda','el son de la noche','el son de la tarde','el son de la brisa','el son de la lluvia','el son de la niebla','el son de la cueva','el son de la plaza','el son de la calle','el son del bosque','el son del río','el rumor del camino','el rumor del molino','el canto del viajero','el canto del lucero','el canto de la aurora','el canto de la espera','el canto de la vida','el canto de la herida','el son de la campana','el son de la ventana','el sueño del ausente','el rastro del viajero','el rastro del lucero']},
 {verb:'busca',objects:['mi canto','tu canto','su canto','mi llanto','tu llanto','el camino','mi destino','el molino','mi sueño','tu sueño','mi risa','tu risa','la calma','mi alma','la fuente','la gente','el presente','el pasado','lo soñado','lo callado','cada día','la alegría','la casa','la rama','la plata','la mesa','la senda','la niebla','la cueva','la mañana','la ventana','la campana','el rumor','el temblor','el color','el fulgor','la flor','el mar','el hogar','el cristal','la canción','la ilusión','el son del molino','el son del camino','el son de la fuente','el son del presente','el son del pasado','el son de la casa','el son de la rama','el son de la mesa','el son de la senda','el rumor del camino','el rumor del molino','el canto del viajero','el canto del lucero','el canto de la aurora','el canto de la espera','el canto de la vida','el canto de la herida','el son de la campana','el son de la ventana','el sueño del ausente','el rastro del viajero']},
 {verb:'canta',objects:['mi canto','tu canto','su canto','mi llanto','tu llanto','mi destino','mi sueño','tu sueño','mi risa','tu risa','el presente','el pasado','lo soñado','lo callado','cada día','la alegría','el rumor','el temblor','el color','el fulgor','la canción','la ilusión','el son del molino','el son del camino','el son de la fuente','el son del presente','el son del pasado','el son de la casa','el son de la rama','el son de la mesa','el son de la senda','el canto del viajero','el canto del lucero','el canto de la aurora','el canto de la espera','el canto de la vida','el canto de la herida','el son de la campana','el son de la ventana','el sueño del ausente']},
 {verb:'teje',objects:['mi canto','tu canto','mi llanto','el camino','mi destino','mi sueño','tu sueño','mi risa','tu risa','la calma','el presente','el pasado','lo soñado','lo callado','la alegría','la plata','la niebla','el rumor','el temblor','el color','el fulgor','la canción','la ilusión','el son del molino','el son del camino','el son de la fuente','el son del presente','el son del pasado','el rumor del camino','el rumor del molino','el canto del viajero','el canto del lucero','el canto de la aurora','el canto de la espera','el canto de la vida','el canto de la herida','el son de la campana','el son de la ventana','el sueño del ausente','el rastro del viajero']}
];
var powers={eco:{name:'Lacre del Eco',label:'ECO +45',bonus:45,description:'+45 si hay versos que riman.'},pulso:{name:'Tinta del Pulso',label:'PULSO +55',bonus:55,description:'+55 si todos los versos tienen la misma medida.'},imagen:{name:'Prisma de Imágenes',label:'IMAGEN +65',bonus:65,description:'+65 con al menos dos recursos literarios distintos.'},constelacion:{name:'Constelación',label:'ESTROFA +90',bonus:90,description:'+90 con una estrofa ABAB, ABBA o AABB.'}};
function build(prosody){var list=[];subjects.forEach(function(subject,si){families.forEach(function(f,fi){f.objects.forEach(function(object,oi){
 var text=subject[0]+' '+f.verb+' '+object,scan=prosody.scan(text);if(scan.syllables!==8&&scan.syllables!==11)return;
 var id='vbank_'+si+'_'+fi+'_'+oi,seed=si*307+fi*83+oi,rarity=seed%67===0?'legendary':seed%29===0?'epic':seed%11===0?'rare':'common';
 var power=rarity==='common'?null:['eco','pulso','imagen','constelacion'][seed%4];
 var assonant=(object==='la casa'||object==='la rama'||object==='la plata'||object==='la mesa'||object==='la senda'||object==='la niebla'||object==='la cueva');
 var rhyme=assonant?scan.last.assonant.split('').join('-'):scan.last.consonant;if(rhyme==='ia')rhyme='ía';
 list.push({id:id,text:text,meter:scan.syllables,rhyme:rhyme,rhymeType:assonant?'asonante':'consonante',theme:subject[1],devices:['personificación'],value:(scan.syllables===11?49:39)+({common:0,rare:15,epic:25,legendary:40}[rarity]),rarity:rarity,power:power,generated:true,reading:scan});
 });});});return list;}
window.VersopolisVerseBank={build:build,powers:powers};
})();
