/** AUTO-GENERATED from config/game-catalog.json. DO NOT EDIT BY HAND. */
const LA_GAME_CATALOG_VERSION = 6;
const LA_ALL_GAMES = [
  {gameId:"battlegrafia",nombre:"Battlegrafía",subtitulo:"La aventura de las palabras",categoria:"RPG",competencias:"ortografía,verbos,semántica",estado:"listo",orden:1,color:"#68d9ff",icono:"⚔️",url:"https://pablogarciablancov.github.io/lenguarcade/games/battlegrafia_v2/",descripcion:"RPG de Lengua con combates, cinco mundos, criaturas, modos de juego y progresión.",banner:"dragon",activo:true,integration:"embedded",official:true},
  {gameId:"maniacgrafia",nombre:"Maniacgrafía",subtitulo:"Atrapa las palabras",categoria:"Ortografía",competencias:"ortografía,acentuación,atención",estado:"listo",orden:2,color:"#d946ef",icono:"⚡",url:"https://pablogarciablancov.github.io/lenguarcade/games/maniacgrafia/",descripcion:"Atrapa y corrige palabras trampa mientras mejoras rapidez y precisión.",banner:"neon",activo:true,integration:"embedded",official:true},
  {gameId:"narratoria",nombre:"Narratoria",subtitulo:"Escribe. Crea. Cuenta.",categoria:"Escritura",competencias:"narración,creatividad,redacción",estado:"listo",orden:3,color:"#f59e0b",icono:"📚",url:"https://pablogarciablancov.github.io/lenguarcade/games/narratoria/",descripcion:"Construye relatos por fases con objetivos, decisiones y creatividad.",banner:"paper",activo:true,integration:"embedded",official:true},
  {gameId:"versopolis",nombre:"Versópolis",subtitulo:"La ciudad de la poesía",categoria:"Poesía",competencias:"poesía,rima,métrica,creatividad",estado:"en pruebas",orden:4,color:"#8b5cf6",icono:"✒️",url:"https://pablogarciablancov.github.io/lenguarcade/games/versopolis/",descripcion:"Duelo poético por rondas: reconoce rimas, métrica y recursos expresivos para conquistar Versópolis.",banner:"versopolis-banner.jpg",activo:true,integration:"embedded",official:true},
  {gameId:"scrabble",nombre:"Scrabble",subtitulo:"Palabras en juego",categoria:"Léxico",competencias:"léxico,vocabulario,estrategia",estado:"listo",orden:5,color:"#34d399",icono:"🔤",url:"https://pablogarciablancov.github.io/lenguarcade/games/scrabble/",descripcion:"Forma palabras, amplía vocabulario y compite usando estrategia verbal.",banner:"board",activo:true,integration:"embedded",official:true},
  {gameId:"conjuga_apuesta",nombre:"Conjuga y apuesta",subtitulo:"Conjuga. Arriesga. Remonta.",categoria:"Verbos",competencias:"verbos,morfología,conjugación,estrategia",estado:"en pruebas",orden:6,color:"#fb7185",icono:"🎲",url:"https://pablogarciablancov.github.io/lenguarcade/games/conjuga_apuesta/",descripcion:"Duelo de conjugación con fichas, niveles de riesgo, rachas, ayudas tácticas, XP y logros.",banner:"dice",activo:true,integration:"embedded",official:true},
  {gameId:"verb_battle",nombre:"Batalla verbal",subtitulo:"Arena táctica de los verbos",categoria:"Verbos",competencias:"verbos,morfología,conjugación,estrategia,equipos",estado:"en pruebas",orden:7,color:"#60a5fa",icono:"⚔️",url:"https://pablogarciablancov.github.io/lenguarcade/games/verb_battle/",descripcion:"Combate por equipos con tablero variable, clases, energía, defensas, runas, eventos, XP y logros.",banner:"battle",activo:true,integration:"embedded",official:true},
  {gameId:"rayuela",nombre:"Rayuela",subtitulo:"Tu historia. Tus decisiones.",categoria:"Escritura",competencias:"narración,creatividad,redacción,coherencia,planificación",estado:"en pruebas",orden:8,color:"#22d3ee",icono:"⌗",url:"https://pablogarciablancov.github.io/lenguarcade/games/rayuela/",descripcion:"Crea y gestiona varias aventuras interactivas con decisiones, objetos, caminos alternativos, pruebas y múltiples finales.",banner:"rayuela",activo:true,integration:"embedded",official:true},
  {gameId:"entre_lineas",nombre:"Entre Líneas",subtitulo:"Agencia de Investigación Lectora",categoria:"Comprensión lectora",competencias:"comprensión,inferencia,síntesis,análisis,coherencia,vocabulario",estado:"en pruebas",orden:9,color:"#d7a942",icono:"🔎",url:"https://pablogarciablancov.github.io/lenguarcade/games/entre_lineas/",descripcion:"Investiga documentos, conecta pistas y demuestra tus hipótesis con evidencias.",banner:"entre_lineas",activo:true,integration:"embedded",official:true},
  {gameId:"tower_defense",nombre:"Guardianes de la Biblioteca",subtitulo:"Defiende la lengua",categoria:"Estrategia lingüística",competencias:"ortografía,verbos,semántica,estrategia",estado:"en pruebas",orden:10,color:"#14b8a6",icono:"🛡️",url:"https://pablogarciablancov.github.io/lenguarcade/games/tower_defense/",descripcion:"Tower defense lingüístico: rompe escudos resolviendo retos de Ortografía, Verbos y Semántica y deja que tus torres derroten a los monstruos.",banner:"tower_defense",activo:true,integration:"embedded",official:true},
  {gameId:"word_play",nombre:"Word Play",subtitulo:"Construye. Combina. Rompe el marcador.",categoria:"Léxico",competencias:"léxico,vocabulario,ortografía,acentuación,estrategia",estado:"listo",orden:11,color:"#22d3ee",icono:"🔠",url:"https://pablogarciablancov.github.io/lenguarcade/games/word_play/",descripcion:"Roguelike de palabras con cartas, tienda, mejoras, misiones lingüísticas, fichas especiales, combos y progresión léxica.",banner:"word-play-banner-v2.webp",activo:true,integration:"embedded",official:true},
  {gameId:"tierras_de_tinta",nombre:"Tierras de Tinta",subtitulo:"Cada palabra es un arma",categoria:"RPG de acción",competencias:"ortografía,morfología,verbos,semántica,literatura,comprensión",estado:"en pruebas",orden:12,color:"#e9a23b",icono:"🖋️",url:"https://pablogarciablancov.github.io/lenguarcade/games/tierras_de_tinta/",descripcion:"RPG de acción y exploración: supera expediciones, derrota criaturas y mejora tu héroe resolviendo desafíos de Lengua.",banner:"tierras-de-tinta-banner.svg",activo:true,integration:"embedded",official:true},
  {gameId:"lexaria",nombre:"Lexaria",subtitulo:"Academia de criaturas lingüísticas",categoria:"Estrategia",competencias:"lengua,léxico,verbos,literatura,estrategia",estado:"en pruebas",orden:13,color:"#4f8cff",icono:"✦",url:"https://pablogarciablancov.github.io/lenguarcade/games/lexaria/",descripcion:"Auto-battler educativo: colecciona Lexarios, entrena con retos de Lengua, crea sinergias y combate en la Academia.",banner:"lexaria-banner.svg",activo:true,integration:"embedded",official:true}
];
const LA_OFFICIAL_GAMES = LA_ALL_GAMES.filter(function(game){ return game.official !== false; });
