/** AUTO-GENERATED from config/game-catalog.json. DO NOT EDIT BY HAND. */
const LA_GAME_CATALOG_VERSION = 1;
const LA_ALL_GAMES = [
  {gameId:"battlegrafia",nombre:"Battlegrafía",subtitulo:"La aventura de las palabras",categoria:"RPG",competencias:"ortografía,verbos,semántica",estado:"en pruebas",orden:1,color:"#f59e0b",icono:"🐉",url:"https://pablogarciablancov.github.io/lenguarcade/games/battlegrafia/",descripcion:"RPG de Lengua con combates, mundos, criaturas y progresión.",banner:"dragon",activo:true,integration:"embedded",official:true},
  {gameId:"battlegrafia_v2",nombre:"Battlegrafía 2.0",subtitulo:"Fantasy Arcade · versión alternativa",categoria:"RPG",competencias:"ortografía,verbos,semántica",estado:"en pruebas",orden:1,color:"#68d9ff",icono:"⚔️",url:"https://pablogarciablancov.github.io/lenguarcade/games/battlegrafia_v2/",descripcion:"Versión alternativa de Battlegrafía en laboratorio, separada de la clásica.",banner:"dragon",activo:false,integration:"embedded",official:false},
  {gameId:"maniacgrafia",nombre:"Maniacgrafía",subtitulo:"Atrapa las palabras",categoria:"Ortografía",competencias:"ortografía,acentuación,atención",estado:"listo",orden:2,color:"#d946ef",icono:"⚡",url:"https://pablogarciablancov.github.io/lenguarcade/games/maniacgrafia/",descripcion:"Atrapa y corrige palabras trampa mientras mejoras rapidez y precisión.",banner:"neon",activo:true,integration:"embedded",official:true},
  {gameId:"narratoria",nombre:"Narratoria",subtitulo:"Escribe. Crea. Cuenta.",categoria:"Escritura",competencias:"narración,creatividad,redacción",estado:"listo",orden:3,color:"#f59e0b",icono:"📚",url:"https://pablogarciablancov.github.io/lenguarcade/games/narratoria/",descripcion:"Construye relatos por fases con objetivos, decisiones y creatividad.",banner:"paper",activo:true,integration:"embedded",official:true},
  {gameId:"versopolis",nombre:"Versópolis",subtitulo:"La ciudad de la poesía",categoria:"Poesía",competencias:"poesía,rima,métrica,creatividad",estado:"en revisión",orden:4,color:"#8b5cf6",icono:"✒️",url:"",descripcion:"Crea poemas, supera retos líricos y progresa como autor dentro de la ciudad de la poesía.",banner:"city",activo:true,integration:"none",official:true},
  {gameId:"scrabble",nombre:"Scrabble",subtitulo:"Palabras en juego",categoria:"Léxico",competencias:"léxico,vocabulario,estrategia",estado:"listo",orden:5,color:"#34d399",icono:"🔤",url:"https://pablogarciablancov.github.io/lenguarcade/games/scrabble/",descripcion:"Forma palabras, amplía vocabulario y compite usando estrategia verbal.",banner:"board",activo:true,integration:"embedded",official:true},
  {gameId:"conjuga_apuesta",nombre:"Conjuga y apuesta",subtitulo:"Conjuga. Arriesga. Remonta.",categoria:"Verbos",competencias:"verbos,morfología,conjugación,estrategia",estado:"en pruebas",orden:6,color:"#fb7185",icono:"🎲",url:"https://pablogarciablancov.github.io/lenguarcade/games/conjuga_apuesta/",descripcion:"Duelo de conjugación con fichas, niveles de riesgo, rachas, ayudas tácticas, XP y logros.",banner:"dice",activo:true,integration:"embedded",official:true},
  {gameId:"verb_battle",nombre:"Batalla verbal",subtitulo:"Arena táctica de los verbos",categoria:"Verbos",competencias:"verbos,morfología,conjugación,estrategia,equipos",estado:"en pruebas",orden:7,color:"#60a5fa",icono:"⚔️",url:"https://pablogarciablancov.github.io/lenguarcade/games/verb_battle/",descripcion:"Combate por equipos con tablero variable, clases, energía, defensas, runas, eventos, XP y logros.",banner:"battle",activo:true,integration:"embedded",official:true},
  {gameId:"rayuela",nombre:"Rayuela",subtitulo:"Tu historia. Tus decisiones.",categoria:"Escritura",competencias:"narración,creatividad,redacción,coherencia,planificación",estado:"en pruebas",orden:8,color:"#22d3ee",icono:"⌗",url:"https://pablogarciablancov.github.io/lenguarcade/games/rayuela/",descripcion:"Crea una aventura interactiva con decisiones, caminos alternativos y múltiples finales.",banner:"rayuela",activo:true,integration:"embedded",official:true},
  {gameId:"entre_lineas",nombre:"Entre Líneas",subtitulo:"Agencia de Investigación Lectora",categoria:"Comprensión lectora",competencias:"comprensión,inferencia,síntesis,análisis,coherencia,vocabulario",estado:"en pruebas",orden:9,color:"#d7a942",icono:"🔎",url:"https://pablogarciablancov.github.io/lenguarcade/games/entre_lineas/",descripcion:"Investiga documentos, conecta pistas y demuestra tus hipótesis con evidencias.",banner:"entre_lineas",activo:true,integration:"embedded",official:true},
  {gameId:"tower_defense",nombre:"Tower Defense",subtitulo:"Defiende la lengua",categoria:"Estrategia lingüística",competencias:"ortografía,verbos,semántica,estrategia",estado:"en revisión",orden:10,color:"#14b8a6",icono:"🛡️",url:"",descripcion:"Detén oleadas de monstruos resolviendo retos lingüísticos antes de que alcancen la base.",banner:"tower_defense",activo:true,integration:"none",official:true}
];
const LA_OFFICIAL_GAMES = LA_ALL_GAMES.filter(function(game){ return game.official !== false; });
